<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE student_details [
	<!ELEMENT student_details (student)*>
	<!ELEMENT student (name, dob, email, college, year_of_study, department, latest_education,about, skills, status)>
	<!ELEMENT name (fname, lname)>
	<!ELEMENT fname (#PCDATA)>
	<!ELEMENT lname (#PCDATA)>
	<!ELEMENT dob (#PCDATA)>
	<!ELEMENT email (#PCDATA)>
	<!ELEMENT college (#PCDATA)>
	<!ELEMENT year_of_study (#PCDATA)>
	<!ELEMENT department (#PCDATA)>
	<!ELEMENT latest_education (school | bachelors | kinder_garden)>
	<!ELEMENT school (#PCDATA)>
	<!ELEMENT bachelors (#PCDATA)>
	<!ELEMENT kinder_garden (#PCDATA)>
	<!ELEMENT about (#PCDATA)>
	<!ELEMENT skills (skill+)>
	<!ELEMENT skill (#PCDATA)>
	<!ELEMENT status (#PCDATA)>
	
	<!ATTLIST student gender (male|female|other) "other">
	<!ATTLIST student roll CDATA #REQUIRED>
	
	<!ENTITY accept "I have read and accepted all terms and conditions">
	<!ENTITY decline "I cannot accept all terms and conditions">
]>

<student_details>
    <student gender="male" roll="123">
	<name>
		<fname>Krishna</fname>
		<lname>Teja</lname>
	</name>
        <dob>12-Aug-99</dob>
        <email>theja@gmail.com</email>
        <college>Amrita University</college>
        <year_of_study>4</year_of_study>
        <department>CSE</department>
		<latest_education>
			<school>Chaitanya CBSE school</school>
		</latest_education>
		<about>I am a web developer</about>
		<skills>
			<skill>HTML</skill>
			<skill>CSS</skill>
		</skills>
		<status>&accept;</status>
	</student>
	<student gender="male" roll="124">
	<name>
		<fname>Pranav</fname>
		<lname>Sudheer</lname>
	</name>
        <dob>11-Feb-99</dob>
        <email>pranv@gmail.com</email>
        <college>Amrita Business &amp; Management studies</college>
        <year_of_study>2</year_of_study>
        <department>Marketing</department>
		<latest_education>
			<bachelors>VIT university</bachelors>
		</latest_education>
		<about>I am a business man</about>
		<skills>
			<skill>Finance</skill>
		</skills>
		<status>&decline;</status>
	</student>
	<student gender="female" roll="125">
	<name>
		<fname>Ranjana</fname>
		<lname>Vaishnav</lname>
	</name>
        <dob>9-Jun-98</dob>
        <email>ranj@gmail.com</email>
        <college>Amrita University</college>
        <year_of_study>5</year_of_study>
        <department>CSE Dual degree</department>
		<latest_education>
			<bachelors>Amrita University</bachelors>
		</latest_education>
		<about>I am &quot;Ranjana Vaishnav&quot;. Currently working as Machine Learning engineer</about>
		<skills>
			<skill>Python</skill>
			<skill>Image Processing</skill>
		</skills>
		<status>&accept;</status>
	</student>
</student_details>